name: CI
on: push
jobs:
  auto-test:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v2 
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: set up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: install and setup pdm
        run: |
          pip install pdm
          pdm config python.use_venv True
        working-directory: app/
      - name: create and activate venv
        run: |
          python3 -m venv ./.venv
          source ./.venv/bin/activate
        working-directory: app/
      - name: pdm install
        run: |
          pdm install -d
          pdm install -G main
        working-directory: app/
      - name: run test
        env: 
          BUCKET_NAME: ${{ secrets.S3_UPLOAD_BUCKET }}
        run: |
          pdm run test
        working-directory: app/